sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v
  - docker-compose build

jobs:
  include:
    - stage: Latest PostgreSQL server
      install:
        - docker-compose run --rm wait
        - docker-compose run --rm app
    - stage: PostgreSQL version 9
      install:
        - docker-compose run --rm wait9
        - docker-compose run --rm app9
    - stage: PostgreSQL version 10
      install:
        - docker-compose run --rm wait10
        - docker-compose run --rm app10
    - stage: PostgreSQL version 11
      install:
        - docker-compose run --rm wait11
        - docker-compose run --rm app11

script:
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD
    quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository
    keboola keboola.ex-db-pgsql`
  - docker tag keboola/ex-db-pgsql:latest $REPOSITORY:master
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD
    quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login
    keboola keboola.ex-db-pgsql)
  - docker push $REPOSITORY:master
  - docker pull quay.io/keboola/syrup-cli:latest
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-pgsql
    285843250 master
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-pgsql
    287599200 master

after_success:
  - docker images

after_error:
  - docker-compose logs

after_failure:
  - docker-compose logs

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true

notifications:
  email: false
  slack:
    secure: CvxTytdizvEesj6OMbcmy24AyduZs1J0kVLp27pzgDhyYhX6GvJwfswmGPyJxa/t6PE9T4Y2XZOD/CUIeUdQXbNmZTlOnGlwaqmihMRX5Kk6xh+VDEcUFZGHM9uLquA6ZWNVj09Pz4KhHAEjVvfy+3PLzv2WnTQ+kYpsGiCenDxMuUyrA1UpLtRFaGxnKnyQfu79rFj49dkR3r+uOe3jaWx45lp3yMTiJdZxqUW2/WnE3WYMd9gaJ3/7oQxkPMUHybp1HGl330nZs/Nxv7cIjsAcW4wgsqm1hfW1ZCvuBl2XRGadgkI+FeFMKDaz/PLV+u9xlE4+lb1pwT7TikILfHqDFNqBXxBpMZIZc09jfSsBs/zEEqIpuquCfMf8cQMcDnNtgd1IoloNJYbrET6HA263DymbdyTn95blqYzNmKTRKXO7qBiU/APrYCUvCj1a9qKKh/zJMd7HOu1e9yn/epEyUECBPxhI8ZJvGrSRhHxxd8EeuB1V5yPNisCo1NkPf/xYRbp+cgSAM3LM3pwIGrG/LwJZD4UzFR7UgHY62aZ5WuSs20rgZaI0XJNvuDFSfcytHLkKqLZgo9gsMrM5ueL7X4jsqkYR8XTbOC2B1qLy5cGAhzJFBOjRc45ule5OQQCxKFrADmth02NcrYQY5Owzgb1txvzpa8MDZzaKihA=
