name: Pull image
description: Pull image from ECR
runs:
  using: "composite"
  steps:
    - name: Pull image from ECR
      shell: bash
      run: |
        echo "PULL: $ECR_URL:${GITHUB_REF##*/} -> $APP_IMAGE"
        echo
        docker pull $ECR_URL:${GITHUB_REF##*/}
        docker tag $ECR_URL:${GITHUB_REF##*/} $APP_IMAGE
