name: GitHub Actions
on: [push]
env:
  APP_IMAGE: keboola/db-extractor-pgsql
  KBC_DEVELOPERPORTAL_VENDOR: "keboola"
  KBC_DEVELOPERPORTAL_APP: "keboola.ex-db-pgsql"
  KBC_DEVELOPERPORTAL_USERNAME: "keboola+github_actions_db_extractor_pgsql"
  KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
  KBC_TEST_PROJECT_URL: "https://connection.keboola.com/admin/projects/2703/dashboard"
  KBC_STORAGE_TOKEN: ${{ secrets.KBC_STORAGE_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Print Docker version
        run: |
          docker -v
      - name: Build image
        run: |
          docker build -t $APP_IMAGE .
      - name: Run test - Latest PostgreSQL server
        run: |
          docker-compose run --rm wait
          docker-compose run --rm app
      - name: Run test - PostgreSQL version 9
        run: |
          docker-compose run --rm wait9
          docker-compose run --rm app9
      - name: Run test - PostgreSQL version 10
        run: |
          docker-compose run --rm wait10
          docker-compose run --rm app10
      - name: Run test - PostgreSQL version 11
        run: |
          docker-compose run --rm wait11
          docker-compose run --rm app11
      - name: Push image to ECR
        run: |
          docker pull quay.io/keboola/developer-portal-cli-v2:latest
          export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
          docker tag $APP_IMAGE:latest $REPOSITORY:test
          eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
          docker push $REPOSITORY:test
          docker pull quay.io/keboola/syrup-cli:latest
      - name: Run KBC test jobs
        run: |
          docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP 285843250 master
          docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP 287599200 master
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: ./deploy.sh
